version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-specialty
    restart: always
    environment:
      POSTGRES_USER: specialty
      POSTGRES_PASSWORD: specialty
      POSTGRES_DB: specialtydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: